### ISSUE TITLE
incorrect file path resolution for $ref

### ISSUE THREAD

**Issue by dbfun** [kirschbaum-development/laravel-openapi-validator#12]
There is a YAML file that contains a link to an example in another JSON file: `$ref: ./examples/errors/unauthenticated.json`

When testing, the following error occurs:

```
Failed to resolve Reference './examples/errors/unauthenticated.json' to  Object: file_get_contents(file:///examples/errors/unauthenticated.json): Failed to open stream: No such file or directory
```

After debugging, I realized that the path is always defined as the root directory:

```php
final class YamlFactory extends StringFactory
{
    public function createSchema(): OpenApi
    {
        $schema = Reader::readFromYaml($this->getContent());

        $schema->resolveReferences(new ReferenceContext($schema, '/')); // <--- HERE
        
        return $schema;
    }
}
```

When I corrected this line the error was fixed:

```php
$schema->resolveReferences(new ReferenceContext($schema, config('openapi_validator.spec_path'))); // /var/www/tests/openapi/
```

The part of the YAML file that causes the error:

```yaml
  responses:
    UnauthorizedError:
      description: Access denied
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Error message
                default: Unauthenticated.
          examples:
            example1:
              value:
                $ref: ./examples/errors/unauthenticated.json
```

**Comment by luisdalmolin** [comment]
This makes sense. The problem right now is that the class that controls this is not from this package, but actually from a dependency, so not that simple to fix. We are definitely open to PRs if you have time to debug it. Otherwise it may take some time until we can get to this.

**Comment by JeroenVanOort** [comment]
I don't have the time to make a PR right now, but I think this could be as easy as changing

`$this->openApiValidatorBuilder = (new ValidatorBuilder())->fromYaml($this->getOpenApiSpec())`
to
`$this->openApiValidatorBuilder = (new ValidatorBuilder())->fromYamlFile($this->getOpenApiSpecPath());`

in `src/ValidatesOpenApiSpec.php`.

As similar function seems available for JSON files. The function `getOpenApiSpec()` wouldn't be used any more. Would need to write some tests for it too.

**Comment by luisdalmolin** [comment]
I tagged version 0.4.0 with this change.
