### ISSUE TITLE
Insanely Slow

### ISSUE THREAD

**Issue by h-sigma** [kirschbaum-development/laravel-openapi-validator#14]
Am I doing something wrong? The `ValidatesOpenApiSec` adds approx 200ms of latency to every test!
Before:
![image](https://github.com/kirschbaum-development/laravel-openapi-validator/assets/52352326/860ff437-7cd1-4ffe-93dd-243b81ef60b7)
After:
![image](https://github.com/kirschbaum-development/laravel-openapi-validator/assets/52352326/a79d8643-aabc-4e1d-a8cc-3659e0f730f4)

The only change is the usage of the trait `use ValidatesOpenApiSpec;`

**Comment by h-sigma** [comment]
For anyone facing this problem: the League open api validator library used internally has a caching mechanism for parsing open api schemas. You simply need to set a cache on the ValidatorBuilder to use that. I use the following trait:
```php
<?php

namespace Tests;

use Illuminate\Support\Facades\Redis;
use League\OpenAPIValidation\PSR7\ValidatorBuilder;
use Symfony\Component\Cache\Adapter\RedisAdapter;

trait ValidatesOpenApiSpec
{
    use \Kirschbaum\OpenApiValidator\ValidatesOpenApiSpec {
        getOpenApiValidatorBuilder as parentGetOpenApiValidatorBuilder;
    }

    public function getOpenApiValidatorBuilder(): ValidatorBuilder
    {
        $builder = $this->parentGetOpenApiValidatorBuilder();
        $builder->setCache(new RedisAdapter(Redis::client()));
        return $builder;
    }
}
```

**Comment by luisdalmolin** [comment]
Thanks, @h-sigma
