### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by Bosbaba** [kirschbaum-development/laravel-openapi-validator#9]
Would appreciate it if you can make the package support Laravel 10
Might just be a case of adding `|^10.0` to `illuminate/support`

`kirschbaum-development/laravel-openapi-validator 0.2.2      requires         illuminate/support (^6.0|^7.0|^8.0|^9.0)`

See you already have a PR open for it 👍🏻

**Comment by tvbeek** [comment]
There are already 2 PR's for this ( #7 and #8 )

I think we just need to wait on @zerodahero to review and merge it.

**Comment by Bosbaba** [comment]
Upgrade was merged, thx guys really appreciate the work
